name: Daily Cleanup

on:
  schedule:
    - cron: "0 21 * * *"   # JST6:00 = UTC21:00
  workflow_dispatch:       # 手動実行も可能

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run cleanup batch
        run: npx ts-node --esm ./batch/index.ts
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
